### ISSUE TITLE
Add github CI for tests

### ISSUE THREAD

**Issue by ostanley** [afids/fidvalidator#12]
Get circle CI or some such to run the tests for json validation.

**Comment by kaitj** [comment]
Just to follow up on this now that I've tried out some flavour of CI and monitoring others...

- If this is ultimately hosted through the Khanlab organization, we can probably make use of CircleCI
- TravisCI is another potential route to go - its free for open source projects - comes with unlimited builds and 3 concurrent jobs. There are a few current organizations that use this.
- After we have determined the final location for this validator, we can sign up for Github Actions for the user / organization. It's not perfect and can still be buggy in some cases, but there are a number of prebuilt workflows.

**Comment by ostanley** [comment]
I assume if we still want to do this we use github actions now?

**Comment by kaitj** [comment]
Yes - i was actually gonna get to this later this morning. Would be good to have all PRs tested before merging

**Comment by kaitj** [comment]
See #55. CI has been implemented along with automatic assignment of reviewer if test is successful.

**Comment by tkkuehn** [comment]
#55 Is merged and addresses this issue, so I'll close it.
