### ISSUE TITLE
Branch clean up

### ISSUE THREAD

**Issue by kaitj** [afids/fidvalidator#51]
Should go through and removing branches that have been merged in or are stale.

**Comment by kaitj** [comment]
Archiving and deleting any branches that have been merged.

There are also some open branches and just a question of if they are still being used or if they should be archived (or just deleted):

- heroku @ostanley 
- d3-script @tkkuehn 
- layout @tkkuehn

**Comment by kaitj** [comment]
An additional comment for someone who has access to the settings of this repo (@Park-Patrick?), if you go in and turn on "Automatically delete head branches", it should automatically delete merged branches in the future.

Here's a screenshot from a different repo:
![image](https://user-images.githubusercontent.com/21226986/69826621-fee5ac80-11e1-11ea-984b-d8b922da1b1b.png)

**Comment by Park-Patrick** [comment]
setting is now changed
