### ISSUE TITLE
Website Bugs

### ISSUE THREAD

**Issue by kaitj** [afids/fidvalidator#67]
A couple of minor issues:

1) The alignment seems to be a little bit off (with new site pushed). You can see it in the screenshot below. It also appears on one of the other pages.

![Screenshot from 2020-02-21 14-11-08](https://user-images.githubusercontent.com/21226986/75064031-26cc6f80-54b4-11ea-8241-63e26784d649.png)

2) Guess we forgot to take out the copyright on the bottom there, but can do that as part of the code cleanup! 

![Screenshot from 2020-02-21 14-11-13](https://user-images.githubusercontent.com/21226986/75064083-41064d80-54b4-11ea-8131-ee5353270ca2.png)

**Comment by kaitj** [comment]
Both of these are fixed in the `code-cleanup`

Thanks @tkkuehn!

**Comment by kaitj** [comment]
See #68

**Comment by tkkuehn** [comment]
Alignment is still off on "Valid file" dialog after successfully uploading a file, I think.

**Comment by kaitj** [comment]
> Alignment is still off on "Valid file" dialog after successfully uploading a file, I think.

Yep, just saw that too. Will see if I can fix it!

**Comment by kaitj** [comment]
Closing with the new merge of #70
